export const productsData = [
    {
        img: "./site-produts/T1374101104100.jpg",
        name: "Tissot",
        price: 50000,
        id: 1,
        description: "Описание часов — это структурированная характеристика устройства для измерения времени, которая включает в себя классификацию, особенности механизма, материалы корпуса, а также набор функциональных возможностей Описание часов — это структурированная характеристика устройства для измерения времени, которая включает в себя классификацию, особенности механизма, материалы корпуса, а также набор функциональных возможностей",
    },
    {
        img: "./site-produts/A159WA-N1.jpg",
        name: "Casio",
        price: 10000,
        id: 2,
    },
    {
        img: "./site-produts/71575ahtSiL._AC_SX679_.jpg",
        name: "Orient",
        price: 30000,
        id: 3,
    },
    {
        img: "./site-produts/1102-0-3-45.jpg",
        name: "NIKA",
        price: 3000000,
        id: 4,
    },
    {
        img: "./site-produts/Rado3.jpg",
        name: "Rado",
        price: 37000,
        id: 5,
    },
    {
        img: "./site-produts/RADO32500328.jpg",
        name: "Rado",
        price: 52000,
        id: 6,
    },
    {
        img: "./site-produts/CITIZENNK5010-51L.jpg",
        name: "Citizen",
        price: 45000,
        id: 7,
    },
    {
        img: "./site-produts/CITIZENAN8190-51L.jpg",
        name: "Citizen",
        price: 23200,
        id: 8,
    },
    {
        img: "./site-produts/SLGA009G.jpg",
        name: "Grand Seiko",
        price: 1500000,
        id: 9,
    },
    {
        img: "./site-produts/Rado3.jpg",
        name: "Rado",
        price: 10000,
        id: 10,
    },
    {
        img: "./site-produts/T1374101104100.jpg",
        name: "Tissot",
        price: 50000,
        id: 11,
    },
    {
        img: "./site-produts/A159WA-N1.jpg",
        name: "Casio",
        price: 10000,
        id: 12,
    },
    {
        img: "./site-produts/71575ahtSiL._AC_SX679_.jpg",
        name: "Orient",
        price: 30000,
        id: 13,
    },
    {
        img: "./site-produts/1102-0-3-45.jpg",
        name: "NIKA",
        price: 3000000,
        id: 14,
    },
    {
        img: "./site-produts/Rado3.jpg",
        name: "Rado",
        price: 10000,
        id: 15,
    },
    {
        img: "./site-produts/CITIZENNK5010-51L.jpg",
        name: "Citizen",
        price: 45000,
        id: 16,
    },
]